name: Build and Push Standard Image
on:
  push:
    branches:
      - master
    paths:
      - 'standard/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'standard/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: false
        default: 'latest'

jobs:
  call-build:
    if: ${{ !vars.USE_GH }}
    uses: ./.github/workflows/build.yml
    permissions:
      id-token: write
      contents: read
      packages: write
    with:
      prefix: standard

  call-build-gh:
    if: ${{ vars.USE_GH == 'true' }}
    uses: ./.github/workflows/build_gh.yml
    permissions:
      id-token: write
      contents: read
      packages: write
    with:
      prefix: standard
