name: Build and Push GPU CUDA Image
on:
  push:
    branches:
      - master
    paths:
      - 'gpu-cuda/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'gpu-cuda/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: false
        default: 'latest'

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    permissions:
      id-token: write
      contents: read
    with:
      prefix: gpu-cuda
